---
title: Code Analysis in R
author: Russ Hyde
date: '2019-06-27'
slug: code-analysis-in-r
categories:
  - R
tags:
  - coding
  - rstats
  - code-analysis
lastmod: '2019-06-27T16:41:20+01:00'
layout: post
type: post
highlight: no
---

**You've been analysing data all day, now let's analyse your code ...**

Within it's programming toolkit, _R_ has some really cool things for analysing
code and for identifying / fixing issues in your code.

What kinds of code-level stuff (eg, software-design/architectural properties,
code smells) might you want to be aware of when developing packages or writing
analysis scripts? And what tools are available to do this?

- Dependencies

    - between packages (`pkgnet`)

    - between functions within a package or script (`pkgnet` / `CodeDepends`, / `codetools`)

- Complexity

    - Labyrinthine functions (`cyclocomp`)

    - Elongated functions

- Style

    - Code formatting (`lintr` / `styler` / `formatR`)

    - Refactorings: alternative (eg, safer / more idiomatic) language
    constructs with similar behaviour (`goodpractice` does a bit of this; but
    _R_ doesn't have much refactoring support)

- Test quality

    - Are all your functions tested? (`covr`)

    - Are your tests good enough? (See `mutate` / `hedgehog`)

- Performance

    - `microbenchmark`, `profvis` etc

- Documentation / Installability / Loadability

    - `R CMD check` / `goodpractice` (for packages at least, running
    `R CMD check` and `goodpractice` should be essential)

... and being aware of these things can help you restructure your code, so that
it's more easily used, maintained and extended.

Code analysis splits neatly into two camps,
[dynamic-](https://en.wikipedia.org/wiki/Dynamic_program_analysis) and
[static-analysis](https://en.wikipedia.org/wiki/Static_program_analysis),
loosely depending on whether your code is ran during the analysis. For example,
you could determine whether all the variable names in a script conform to some
style guide without having to run that script (static); but you'd need to run
a script to work out which function calls have the largest appetite for
processor time or memory (dynamic).

In the following posts, I'm going to explain how to use these tools (and a
couple of tools that are less well developed) on your analysis scripts or
packages.

In the face of these automatic code-analysis tools, it's important to remember
that there's no real substitute for getting a human to code-review your stuff,
because there isn't any automated way to address the most important thing: code
readability.

<!--
  For each of the tools, describe
  - The package & author
  - Any existing blog posts or vignettes that describe how to use it
  - The architectural property or code smell that the package can help you
  quantify or address and why addressing _that_ matters
  - A brief example of how to use it, either:
    - against a script
    - against a package
    - against a set of packages
  - Does the tool
    - directly modify your source code?
    - run your source code?
    - require tests to be in place before running?
  
-->

<!--

## Notes

Here, I'm more interested in code correctness, design and style than speed or
RAM usage.

Prospective packages:

- `mutate` from rOpenSci

- `dupree` from me

Things that can be done in other languages that aren't (yet? / to my knowledge)
available or possible in R:

- type-checking

- unused code detection

- refactoring recommendations (? this is done by goodpractice)

- security problems

But 
--> 

## Resources

"Nice R Code" has a
[blog post](https://nicercode.github.io/blog/2013-05-07-how-long-is-a-function/)
on function lengths in R packages and also a post about why nice code is
[something to strive for](https://nicercode.github.io/blog/2013-04-05-why-nice-code/).

The Software Sustainability Institute also has a webpage about source code
[readability](https://software.ac.uk/resources/guides/writing-readable-source-code).

Maelle Salmon from rOpenSci has a nice
[blog post](https://masalmon.eu/2017/12/11/goodrpackages/) that covers some
tools that help during package development.

For more on "code smells" see Martin Fowler's "Refactoring", Robert C. Martin's
"Clean Code" or Jenny Bryan's
[useR!2018 talk](https://github.com/jennybc/code-smells-and-feels#readme).

Some code smells that are particularly relevant here pave the many rings of 
[the _R_ inferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf).

There's a list of the different aspects of software architecture
[here](https://medium.com/@nvashanin/quality-attributes-in-software-architecture-3844ea482732).

<!--

## Code smells

[As named in _Refactoring_] if relevant to data analysis or _R_ packages

- Naming

    - Mysterious name

- Comments

- Code structure

    - Duplicated code

    - Repeated switches

    - Loops

    - Temporary field

- Functions

    - Long function

    - Long parameter list

    - Speculative generality

- Data and variables

    - Global data

    - Mutable data

    - Data clumps

    - Primitive obsession

    - Data class

- Coupling / cohesion and other dependencies

    - Feature envy

    - Message chains

    - Middle man

- Revealed during modification / generalisation

    - Divergent change

    - Shotgun surgery

???
- Lazy element

- Insider trading

- Large class

- Alternative classes with different interfaces

- Refused bequest
-->